# Generated by Django 5.0.4 on 2024-04-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="telephone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("make", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
            ],
            options={
                "db_table": "telephone",
            },
        ),
    ]
