# Generated by Django 5.0.4 on 2024-04-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
